### ISSUE TITLE
How do I edit this in Dreamweaver

### ISSUE THREAD

**Issue by danielpavey** [jcodo/index.php#1]
How do I edit this framework in Dreamweaver....???

Your instructions do not explain...!!! 😠

**Comment by jcodo** [comment]
Cannot recreate. Closing

**Comment by PhilipRowe** [comment]
@danielpavey Have you tried notepad.exe? I have heard that it can be opened in that....

**Comment by danielpavey** [comment]
I have just upgraded from Frontpage and do not wish to change again...

Notepad.exe is far to complex an IDE anyway.... 

Please update your framework to support Dreamweaver 😡

**Comment by jcodo** [comment]
![giphy](https://user-images.githubusercontent.com/43956180/57624306-91499a00-7589-11e9-80a0-a48048f58674.gif)

**Comment by danielpavey** [comment]
![away-with-the-faries](https://user-images.githubusercontent.com/18568935/57624400-bf2ede80-7589-11e9-9817-603651ef81cc.gif)
